apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-base
  namespace: argocd
  labels:
    app: dev-base
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/Bionic-AI-Solutions/dev-base.git
    targetRevision: main
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
