apiVersion: v1
kind: Service
metadata:
  name: dev-base-ssh
  namespace: dev-base
  labels:
    app: dev-base
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
    protocol: TCP
    name: ssh
  selector:
    app: dev-base
