apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: dev-base-production

namespace: dev-base

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

commonLabels:
  environment: production

images:
  - name: docker4zerocool/dev-base
    newTag: latest