apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-base-pvc
  namespace: dev-base
  labels:
    app: dev-base
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
